# Generated by Django 5.1.6 on 2025-02-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_flight_crew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(related_name="flights", to="airport.crew"),
        ),
    ]
