# Generated by Django 5.1.6 on 2025-02-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_flight_crew"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["-departure_time"]},
        ),
    ]
