# Generated by Django 5.1.6 on 2025-02-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_alter_flight_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["departure_time"]},
        ),
    ]
