# Generated by Django 5.1.6 on 2025-02-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_alter_flight_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
    ]
