# Generated by Django 5.1.6 on 2025-02-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airplanetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
